version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '21:00'
  open-pull-requests-limit: 10
  reviewers:
    - vinayakkulkarni
  assignees:
    - vinayakkulkarni
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '21:00'
  open-pull-requests-limit: 10
  reviewers:
    - vinayakkulkarni
  assignees:
    - vinayakkulkarni
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
